Can login + see home (hidden full home for now)
fedeagripa/TargetMVD_React pull request #1
Opened 2017-04-21 18:47 UTC by fedeagripa

2017-04-21 19:26 UTC, felipegarcia92 requested changes
Nice, clean first PR 👏 👍 

Minor syntax comments and you're ready to go.

2017-04-21 19:26 UTC, felipegarcia92 commented on src/components/chat/ChatLine.js
> +      <img src={littleSmilies}   className="bitmap"/>
I think you have an extra space between `{littleSmilies}` and `className`. The same applies to a couple of lines below

2017-04-21 19:26 UTC, felipegarcia92 commented on src/components/chat/ChatLine.js
> +      <b> {name} </b>
Remove spaces around `{name}` unless you want them to appear in your page. Check for the same thing in other tags in this PR.

2017-04-24 12:56 UTC, bernabe9 requested changes
Looks good for a first PR!

2017-04-24 12:56 UTC, bernabe9 commented on src/components/chat/ChatLine.js
> +    <div className="light-line"></div>
You can self-close the tags that have not children. (https://github.com/airbnb/javascript/tree/master/react#tags)

Also, are you running the linter? I think that the linter should be warn about this

2017-04-24 12:56 UTC, bernabe9 commented on src/components/chat/ChatLine.js
> +    <div className="light-line"></div>
Another thing.. The correct html tag to make a line is the `hr` tag instead of a `div`. https://www.w3schools.com/tags/tag_hr.asp

2017-04-24 12:56 UTC, bernabe9 commented on src/components/navbar/HomeNav.js
> +import avatar_example from '../../assets/avatar-example.svg';
Always use camel case in javascript. I mean `avatarExample` instead of `avatar_example`

2017-04-24 12:56 UTC, bernabe9 commented on src/styles/media.scss
> +  padding: 2rem;
Keep consistent with the units, use `rem` or `px` but not both. I prefer to use `rem`  but I saw that there are more `px` units, so it's your call

2017-04-25 17:15 UTC, bernabe9 commented on src/containers/HomePage.js
> +/*import LogoutButton from '../components/session/LogoutButton';*/
remove commented line

2017-04-25 17:15 UTC, bernabe9 commented on src/containers/NavBar.js
> +/*import HomeNav from '../components/navbar/HomeNav';*/
same

2017-04-25 17:33 UTC, bernabe9 approved these changes

2017-04-26 14:59 UTC, felipegarcia92 approved these changes
Approving even though you have horrible commented lines, since you said that's forecoming and wanted to keep them.

2017-06-23 13:39 UTC, merged